"""Compare independently decoded native skinning against the GLB source poses."""
import json,re
from pathlib import Path
import numpy as np
from PIL import Image
from pdx_binary import read,write
from export_goblin_models import GLB,ART,MODEL_REL,FLIP,ROOT,trs

def verify(out,game=None):
    out=Path(out);folder=out/MODEL_REL;g=GLB(ART/'variants/cindermaw.glb')
    tree=read(folder/'cm_goblin_cindermaw.mesh');shape=tree['children'][0]['children'][0]
    bones=next(n for n in shape['children'] if n['name']=='skeleton')['children']
    meshes=[n for n in shape['children'] if n['name']=='mesh'];assert len(meshes)==len(g.primitives())
    parents=[n['props'].get('pa',('i',[-1]))[1][0] for n in bones]
    assert all(p<i for i,p in enumerate(parents))
    inverses=[]
    for n in bones:
        m=np.eye(4);m[:3,:]=np.array(n['props']['tx'][1]).reshape(4,3).T;inverses.append(m)
    assert [n['name'] for n in bones]==g.names
    maximum=0.;poses=0;triangles=0
    for mesh,p in zip(meshes,g.primitives()):
        xyz=np.array(mesh['props']['p'][1]).reshape(-1,3);norm=np.array(mesh['props']['n'][1]).reshape(-1,3)
        ix=np.array(mesh['props']['tri'][1]);assert ix.min()>=0 and ix.max()<len(xyz);triangles+=len(ix)//3
        assert np.isfinite(xyz).all() and np.allclose(np.linalg.norm(norm,axis=1),1,atol=1e-5)
        skin=next(n for n in mesh['children'] if n['name']=='skin')['props']
        weights=np.array(skin['w'][1]).reshape(-1,4);ids=np.array(skin['ix'][1]).reshape(-1,4)
        assert np.allclose(weights.sum(axis=1),1,atol=1e-6) and ids.max()<len(bones)
    for anim in g.g['animations']:
        native=read(folder/('cm_goblin_'+anim['name']+'.anim'));info,streams=native['children']
        count=info['props']['sa'][1][0];joint_count=info['props']['j'][1][0]
        assert joint_count==len(bones) and [n['name'] for n in info['children']]==g.names
        data={k:np.array(streams['props'][k][1]).reshape(count,joint_count,width) for k,width in [('t',3),('q',4),('s',1)]}
        assert all(np.isfinite(x).all() for x in data.values())
        assert np.allclose(np.linalg.norm(data['q'],axis=2),1,atol=1e-5)
        duration=max(float(g.access(s['input'])[-1,0]) for s in anim['samplers'])
        for frame in sorted({0,(count-1)//2,count-1}):
            world=[]
            for i in range(len(bones)):
                m=trs(data['t'][frame,i],data['q'][frame,i],np.repeat(data['s'][frame,i],3))
                world.append(world[parents[i]]@m if parents[i]>=0 else m)
            source_pose=g.pose(anim,duration*frame/(count-1))
            for mesh,p in zip(meshes,g.primitives()):
                a=p['attributes'];original=np.c_[g.access(a['POSITION']),np.ones(len(g.access(a['POSITION'])))]
                source_ids=g.access(a['JOINTS_0']).astype(int);source_w=g.access(a['WEIGHTS_0']).astype(float);source_w/=source_w.sum(axis=1)[:,None]
                expected=np.zeros_like(original)
                for influence in range(4):
                    matrices=np.array([source_pose[j]@g.ibm[k] for k,j in enumerate(g.skin['joints'])])[source_ids[:,influence]]
                    expected+=np.einsum('nij,nj->ni',matrices,original)*source_w[:,influence,None]
                expected=(FLIP@expected.T).T[:,:3]
                xyz=np.c_[np.array(mesh['props']['p'][1]).reshape(-1,3),np.ones(len(original))]
                skin=next(n for n in mesh['children'] if n['name']=='skin')['props']
                ids=np.array(skin['ix'][1]).reshape(-1,4);weights=np.array(skin['w'][1]).reshape(-1,4)
                actual=np.zeros_like(xyz)
                for influence in range(4):
                    matrices=np.array([world[i]@inverses[i] for i in range(len(bones))])[ids[:,influence]]
                    actual+=np.einsum('nij,nj->ni',matrices,xyz)*weights[:,influence,None]
                error=float(np.max(np.linalg.norm(actual[:,:3]-expected,axis=1)));maximum=max(maximum,error)
                assert error<.03,(anim['name'],frame,error)
            poses+=1
    roundtrips=0
    # Exact native round trips verify the independent parser/writer against
    # installed engine data, not only files generated by this exporter.
    if game:
        game=Path(game);temp=ROOT/'.local/pdx_roundtrip';temp.mkdir(parents=True,exist_ok=True)
        for rel in ['in_game/gfx/models/units/unit_skeleton.mesh','in_game/gfx/models/units/animations/unit_drowning.anim']:
            original=game/rel;target=temp/original.name;write(target,read(original));assert target.read_bytes()==original.read_bytes();roundtrips+=1
    clan_count=0
    for p in folder.glob('cm_goblin_*.mesh'):
        candidate=read(p);assert candidate==tree,'Clan geometry should be shared; palettes are external textures';clan_count+=1
    assert clan_count==5 and triangles==2476
    config=json.loads((ART/'clans.json').read_text())
    constructors=(out/'main_menu/gfx/unit_graphics/units/zz_ashborn_goblins.txt').read_text()
    for clan in config['clans']:
        stem='cm_goblin_'+clan['id'];tag=clan['culture']+'_gfx'
        color=Image.open(folder/(stem+'_0_diffuse.dds')).convert('RGBA').getpixel((0,0))
        expected=tuple(bytes.fromhex(clan['skin_srgb'][1:]))+(255,)
        assert color==expected,(clan['id'],color,expected)
        assert f'{tag}:army_light_infantry' in constructors and f'{tag}:army_heavy_infantry' in constructors
        asset=(folder/(stem+'.asset')).read_text()
        for texture in re.findall(r'"([^"\n]+\.dds)"',asset):assert (folder/texture).is_file()
        for clip in re.findall(r'type = "([^"\n]+\.anim)"',asset):assert (folder/clip).is_file()
        schematic=(out/'in_game/gfx/models/schematics'/(stem+'_schematic.schematic')).read_text()
        ids=set(re.findall(r'(?<!_)\bid=(\d+)',schematic));links=set(re.findall(r'linked_node=(\d+)',schematic));assert links<=ids
        assert 'mesh_components' in schematic and 'skeleton' in schematic and 'state_machine_components' in schematic
    machine=(out/'main_menu/gfx/animation_state_machines/cm_goblin_infantry.animsm').read_text()
    for clip in re.findall(r'animation="([^"]+)"',machine):assert (folder/(clip+'.anim')).is_file()
    for path in list(folder.glob('*.asset'))+list((out/'in_game/gfx/models/schematics').glob('cm_goblin_*.schematic')):
        text=path.read_text();assert text.count('{')==text.count('}')
    return {'status':'STATIC MODEL CHECKS PASSED; ENGINE PLAYTEST PENDING','clans':clan_count,'source_joints':23,'exported_bones':len(bones),'triangles_per_clan':triangles,'animations':len(g.g['animations']),'sampled_poses':poses,'maximum_pose_error_cm':maximum,'native_byte_exact_roundtrips':roundtrips,'palettes_and_runtime_references':True,'engine_tested':False}

if __name__=='__main__':
    import argparse
    ap=argparse.ArgumentParser();ap.add_argument('--out',type=Path,default=ROOT/'build/goblin_models');ap.add_argument('--game',type=Path);args=ap.parse_args()
    report=verify(args.out,args.game);(args.out/'model_verification.json').write_text(json.dumps(report,indent=2));print(json.dumps(report,indent=2))
